# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master, dev]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    continue-on-error: ${{ matrix.config.must_pass }}

    strategy:
      fail-fast: false
      matrix:
        config:
          # Latest R versions on all OSs
          - {os: macOS-latest,    r: 'release', must_pass: false}
          - {os: windows-latest,  r: 'release', must_pass: true}
          - {os: ubuntu-latest,   r: 'release', must_pass: true}

          # Development and recent releases
          - {os: ubuntu-latest, r: 'devel', http-user-agent: 'release', must_pass: false}
          - {os: ubuntu-latest, r: 'oldrel-1', must_pass: true}
          - {os: ubuntu-latest, r: 'oldrel-2', must_pass: true}

          # An approximation for the PHS RStudio Desktop installation
          - {os: windows-latest,  r: '3.6.1', must_pass: true}

          # An approximation of the PHS RStudio Server Pro setup
          - {os: ubuntu-latest,   r: '3.6.1', must_pass: true}
          - {os: ubuntu-latest,   r: '3.5.1', must_pass: false}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: rcmdcheck

      - uses: r-lib/actions/check-r-package@v1

      - name: Show testthat output
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check
