on:
  push:
    paths:
      - 'README.Rmd'
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - uses: r-lib/actions/pr-fetch@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
         use-public-rspm: true

      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: rmarkdown

      - name: Re-knit README.Rmd
        run: rmarkdown::render('README.Rmd')

      - name: Commit the results
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Re-knit README.md after changes to the .rmd file (GitHub action)
